# p6 (error code) - 8
# initialize the amount variable
try:
    print(x)
except:
    print("Something went wrong")
finally:
    print("The 'try except' is finished")
# output - Hello\nNothing went wrong
#ans -X is not declared so it will give NameError and resolve it in except block